<?php

namespace FrontendBundle\Repository;

/**
 * CsOddsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsOddsRepository extends \Doctrine\ORM\EntityRepository
{
}
