<?php

namespace FrontendBundle\Repository;

/**
 * InjuryUpdatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InjuryUpdatesRepository extends \Doctrine\ORM\EntityRepository
{
}
