<?php

namespace FrontendBundle\Repository;

/**
 * PriceChangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProbablePriceChangesRepository extends \Doctrine\ORM\EntityRepository
{
}
