# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    sonata.admin.security.mask.builder.class: Sonata\AdminBundle\Security\Acl\Permission\MaskBuilder
services:
   admin.article:
        class: ArticleBundle\Admin\ArticleAdmin
        arguments: [~, ArticleBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article }
        roles: [ ROLE_EDITOR ]
        public: true
   admin.paragraph:
        class: ArticleBundle\Admin\ParagraphAdmin
        arguments: [~, ArticleBundle\Entity\Paragraph, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Paragraph }
        public: true
   admin.news:
        class: FrontendBundle\Admin\NewsAdmin
        arguments: [~, FrontendBundle\Entity\News, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: News }
        public: true
   admin.team:
        class: FrontendBundle\Admin\TeamAdmin
        arguments: [~, FrontendBundle\Entity\Team, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Team }
        public: true
   admin.injury_updates:
        class: FrontendBundle\Admin\InjuryUpdatesAdmin
        arguments: [~, FrontendBundle\Entity\InjuryUpdates, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: injury updates }
        public: true
   admin.csodds:
        class: FrontendBundle\Admin\CsOddsAdmin
        arguments: [~, FrontendBundle\Entity\CsOdds, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CS Odds}
        public: true
   admin.pricechange:
        class: FrontendBundle\Admin\PriceChangesAdmin
        arguments: [~, FrontendBundle\Entity\PriceChanges, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Pre-Season }
        public: true
   admin.propablepricechanges:
        class: FrontendBundle\Admin\ProbablePriceChangesAdmin
        arguments: [~, FrontendBundle\Entity\ProbablePriceChanges, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: propable Pre-Season }
        public: true
   security.acl.permission.map:
       class: Sonata\AdminBundle\Security\Acl\Permission\AdminPermissionMap
