<?php

namespace ArticleBundle\Repository;

/**
 * ParagraphRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParagraphRepository extends \Doctrine\ORM\EntityRepository
{
}
